# Generated by Django 3.0.8 on 2020-09-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='studentd.Student'),
        ),
    ]
