# Generated by Django 3.0.8 on 2020-09-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentd', '0005_auto_20200912_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='physics',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='stid',
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='studentd.Marks'),
        ),
    ]
