# Generated by Django 3.0.8 on 2020-09-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentd', '0006_auto_20200913_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='chemistry',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='maths',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='physics',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
