# Generated by Django 3.0.8 on 2020-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentd', '0007_auto_20200913_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='physics',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
