# Generated by Django 3.0.8 on 2020-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentd', '0008_auto_20200913_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='chemistry',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
